task:
  name: tests-linux
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  script: scripts/verify_tests_on_master.sh
  container:
    image: gcc:latest

task:
  name: tests-windows-0
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  script: scripts\verify_tests_on_master.bat --shards 3 --shard-index 0
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019

task:
  name: tests-windows-1
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  script: scripts\verify_tests_on_master.bat --shards 3 --shard-index 1
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019

task:
  name: tests-windows-2
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  script: scripts\verify_tests_on_master.bat --shards 3 --shard-index 2
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019

task:
  name: tests-macos
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  script: scripts/verify_tests_on_master.sh
  osx_instance:
    image: mojave-base

task:
  name: skp_generator
  use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_PR == ''
  script: (cd skp_generator && ./build.sh)
  container:
    image: gcc:latest
